# version: 0.2
# frontend:
#   phases:
#     preBuild:
#       commands:
#         - npm ci --cache .npm --prefer-offline
#     build:
#       commands:
#         - npm run build
#   artifacts:
#     baseDirectory: .next
#     files:
#       - '**/*'
#   cache:
#     paths:
#       - .next/cache/**/*
#       - .npm/**/*

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci --cache .npm --prefer-offline
  build:
    commands:
      - npm run build
artifacts:
  base-directory: .next
  files:
    - '**/*'
cache:
  paths:
    - .next/cache/**/*
    - .npm/**/*